// EECS 348 Assignment 1
// Program that prioritizes emails for a busy CEO by using maxheap to implement a priority queue. Emails will be placed in queue based on sender category, subject line, and date.
// Inputs: Email and command txt file
// Outputs: command line output that gives information about emails and the amount left to read
// Source: Generated by Claude
// Author: Madelyn Armitage
// Creation Date: 09/16/2026
// No collaborators



//Claude code starts below this line

/* ============================================================
* email_priority.c
*
* Prioritizes a CEO's inbox using a MaxHeap-based priority queue.
*
* The MaxHeap is implemented from scratch as a dynamically-growing
* array (a "list-based" heap, as opposed to a pointer/tree-based
* heap). No standard-library or third-party heap module is used --
* every heap operation below (insert, extract-max, sift up/down)
* is written by hand.
*
* -------------------------------------------------------------
* Priority rules
* -------------------------------------------------------------
* 1. Sender category determines the primary priority:
*        Boss            (highest / read first)
*        Subordinate
*        Peer
*        ImportantPerson
*        OtherPerson     (lowest / read last)
*
* 2. When two queued emails share the same category, the NEWER
*    email (by date) is read first.
*
* Both rules are folded into a single numeric key so a standard
* MaxHeap comparison (bigger key = higher priority) handles both
* at once:
*
*        key = categoryRank * 100000000  +  YYYYMMDD
*
* Category rank dominates the comparison (it's multiplied by a
* number bigger than any possible YYYYMMDD value), so category
* always wins first; the date only breaks ties within the same
* category.
*
* -------------------------------------------------------------
* Commands (one per line of the test file)
* -------------------------------------------------------------
*   EMAIL <sender category>,<subject line>,<date>
*          -> insert a new email into the heap
*   NEXT
*          -> PEEK at (do not remove) the highest-priority email
*             and print Sender / Subject / Date. Calling NEXT
*             twice in a row with no READ in between prints the
*             same email both times, since nothing was removed.
*   READ
*          -> POP the highest-priority email off the heap. Prints
*             nothing (the CEO "dealt with it" silently). Calling
*             READ twice in a row with no NEXT in between simply
*             discards the two highest-priority emails, neither
*             of which is ever displayed.
*   COUNT
*          -> print how many unread emails remain in the queue
*
* NEXT/READ on an empty queue is handled gracefully (no crash,
* a friendly message instead of a listing).
*
* -------------------------------------------------------------
* Running
* -------------------------------------------------------------
*   ./email_priority < testfile.txt      (read commands via stdin)
*   ./email_priority testfile.txt        (read commands from a file
*                                          named on the command line)
* Both invocation styles are supported so the grader can use
* whichever it prefers.
* ============================================================ */

#include <stdio.h> //includes standard input and output library
#include <stdlib.h> //provides dynamic memory from library
#include <string.h> //provides string functions like comparison, copying, and splitting
#include <ctype.h> //provides whitespace character detection

#define MAX_SENDER_LEN   16 //sets max sender length to 16 including null terminator
#define MAX_SUBJECT_LEN  256 //sets max subject length to 256 including null terminator
#define MAX_DATE_LEN     11 //sets max date length to 11 including null terminator
#define MAX_LINE_LEN     1024 //sets max line length to 1024 including null terminator
#define INITIAL_CAPACITY 16 //sets initial capacity to 16 including null terminator
#define CATEGORY_PRIORITY_MULTIPLIER 100000000L //ensures sender rank takes priority over date

/* ------------------------------------------------------------
* Email record stored in the heap.
* ------------------------------------------------------------ */
//email structure that defines characteristics of an email type
typedef struct {//opens email structure
   char sender[MAX_SENDER_LEN];    /* sender category, e.g. "Boss"   */
   char subject[MAX_SUBJECT_LEN];  /* subject line (no commas)       */
   char date[MAX_DATE_LEN];        /* MM-DD-YYYY, kept as given       */
   long priorityKey;               /* combined category+date sort key */
   unsigned long arrivalOrder; //stores arrival order to compare priority ties
} Email;// Allows the usage of name "Email" for the structure type

/* ------------------------------------------------------------
* MaxHeap: a growable array of Emails plus a logical size.
* ------------------------------------------------------------ */
typedef struct { //opens up MaxHeap structure
   Email *data; //points to the email array, specifically the first element in the array
   int size; //keeps track of the number of emails stored in the heap
   int capacity; //keeps track of the number of emails that can fit before resizing
} MaxHeap; //gives name MaxHeap to structure

/* ============================================================
* Heap helper / core functions -- all written from scratch.
* ============================================================ */

/* Allocate the heap's backing array. */
void heapInit(MaxHeap *heap) { //initializes an empty MaxHeap
   heap->capacity = INITIAL_CAPACITY; //reserves space for 16 emails
   heap->size = 0; //heap begins with no stored emails
   heap->data = (Email *)malloc(sizeof(Email) * (size_t)heap->capacity); //makes memory used dynamic based on email amount
   if (heap->data == NULL) { //checks if memory allocation failed
       fprintf(stderr, "Fatal: memory allocation failed in heapInit.\n"); //prints an error if one occured
       exit(1); //ends program if there is an error
   }
}

/* Release everything the heap owns. */
void heapFree(MaxHeap *heap) { //releases heap's allocated memory
   free(heap->data); //Returns the allocated email array to the system
   heap->data = NULL; // Prevents the pointer from referencing freed memory
   heap->size = 0;
   heap->capacity = 0;
}

/* Double the backing array's capacity when it fills up. */
void heapGrow(MaxHeap *heap) {
   int newCapacity = heap->capacity * 2;
   Email *newData = (Email *)realloc(heap->data, sizeof(Email) * (size_t)newCapacity);
   if (newData == NULL) {
       fprintf(stderr, "Fatal: memory allocation failed in heapGrow.\n");
       exit(1);
   }
   heap->data = newData;
   heap->capacity = newCapacity;
}

void swapEmails(Email *first, Email *second) {
   Email temporary = *first;
   *first = *second;
   *second = temporary;
}

static int hasHigherPriority(const Email *first, const Email *second) {
   if (first->priorityKey != second->priorityKey) {
       return first->priorityKey > second->priorityKey;
   }
   return first->arrivalOrder < second->arrivalOrder;
}

/* Restore heap order by moving the element at 'index' upward
* toward the root while it is bigger than its parent. */
void siftUp(MaxHeap *heap, int index) {
   while (index > 0) {
       int parent = (index - 1) / 2;
       if (hasHigherPriority(&heap->data[index], &heap->data[parent])) {
           swapEmails(&heap->data[index], &heap->data[parent]);
           index = parent;
       } else {
           break;
       }
   }
}

/* Restore heap order by moving the element at 'index' downward,
* always swapping with the larger of its two children, until
* both children (if any) are smaller or it has none. */
void siftDown(MaxHeap *heap, int index) {
   while (1) {
       int left = 2 * index + 1;
       int right = 2 * index + 2;
       int largest = index;

       if (left < heap->size &&
           hasHigherPriority(&heap->data[left], &heap->data[largest])) {
           largest = left;
       }
       if (right < heap->size &&
           hasHigherPriority(&heap->data[right], &heap->data[largest])) {
           largest = right;
       }
       if (largest == index) {
           break;
       }
       swapEmails(&heap->data[index], &heap->data[largest]);
       index = largest;
   }
}

/* Insert a new email into the heap, keeping heap order. */
void heapInsert(MaxHeap *heap, Email email) {
   if (heap->size == heap->capacity) {
       heapGrow(heap);
   }
   heap->data[heap->size] = email;
   siftUp(heap, heap->size);
   heap->size++;
}

/* Remove and return the highest-priority email.
* Returns 1 and fills *out on success, 0 if the heap is empty. */
int heapRemoveMax(MaxHeap *heap) {
   if (heap->size == 0) {
       return 0;
   }
   heap->size--;
   if (heap->size > 0) {
       heap->data[0] = heap->data[heap->size];
       siftDown(heap, 0);
   }
   return 1;
}

/* Look at the highest-priority email without removing it.
* Returns 1 and fills *out on success, 0 if the heap is empty. */
const Email *heapPeek(const MaxHeap *heap) {
   if (heap->size == 0) {
       return NULL;
   }
   return &heap->data[0];
}

/* ============================================================
* Parsing helpers
* ============================================================ */

/* Trim leading/trailing whitespace from a string, in place. */
void trim(char *str) {
   int start = 0;
   while (isspace((unsigned char)str[start])) {
       start++;
   }
   if (start > 0) {
       memmove(str, str + start, strlen(str) - (size_t)start + 1);
   }
   int len = (int)strlen(str);
   while (len > 0 && isspace((unsigned char)str[len - 1])) {
       str[len - 1] = '\0';
       len--;
   }
}

/* Map a sender category string to its priority rank.
* Higher number = higher priority = read sooner. */
int categoryRank(const char *category) {
   if (strcmp(category, "Boss") == 0)            return 5;
   if (strcmp(category, "Subordinate") == 0)      return 4;
   if (strcmp(category, "Peer") == 0)             return 3;
   if (strcmp(category, "ImportantPerson") == 0)  return 2;
   if (strcmp(category, "OtherPerson") == 0)      return 1;
   return 0; /* unrecognized category: treated as lowest priority */
}

/* Convert MM-DD-YYYY into a comparable integer YYYYMMDD.
* Bigger result = later (more recent) date. */
long dateToInt(const char *date) {
   int month = 0;
   int day = 0;
   int year = 0;
   char extraCharacter;
   if (sscanf(date, "%d-%d-%d%c", &month, &day, &year,
              &extraCharacter) != 3) {
       return 0;
   }
   if (month < 1 || month > 12 || day < 1 || day > 31 || year < 1) {
       return 0;
   }
   return (long)year * 10000L + (long)month * 100L + (long)day;
}

/* Parse a line of the form:
*     EMAIL <sender category>,<subject line>,<date>
* (commas are the field delimiters; the subject line itself is
* guaranteed not to contain commas) and insert it into the heap. */
void processEmailCommand(MaxHeap *heap, char *line,
                         unsigned long arrivalOrder) {
   /* Skip the leading "EMAIL " token. */
   char *emailData = line + 6;

   char *senderField  = strtok(emailData, ",");
   char *subjectField = strtok(NULL, ",");
   char *dateField    = strtok(NULL, ",");

   if (senderField == NULL || subjectField == NULL || dateField == NULL) {
       fprintf(stderr, "Skipping malformed EMAIL line: %s\n", line);
       return;
   }

   Email email;
   strncpy(email.sender, senderField, MAX_SENDER_LEN - 1);
   email.sender[MAX_SENDER_LEN - 1] = '\0';
   trim(email.sender);

   strncpy(email.subject, subjectField, MAX_SUBJECT_LEN - 1);
   email.subject[MAX_SUBJECT_LEN - 1] = '\0';
   trim(email.subject);

   strncpy(email.date, dateField, MAX_DATE_LEN - 1);
   email.date[MAX_DATE_LEN - 1] = '\0';
   trim(email.date);

   int rank = categoryRank(email.sender);
   if (rank == 0) {
       fprintf(stderr, "Skipping email with invalid sender category: %s\n",
               email.sender);
       return;
   }

   long dateVal = dateToInt(email.date);
   if (dateVal == 0) {
       fprintf(stderr, "Skipping email with invalid date: %s\n", email.date);
       return;
   }

   email.priorityKey =
       (long)rank * CATEGORY_PRIORITY_MULTIPLIER + dateVal;
   email.arrivalOrder = arrivalOrder;

   heapInsert(heap, email);
}

/* ============================================================
* Command handlers
* ============================================================ */

void handleNext(const MaxHeap *heap) {
   const Email *email = heapPeek(heap);
   if (email == NULL) {
       printf("No emails to read.\n\n");
       return;
   }

   printf("Next email:\n");
   printf("\tSender: %s\n", email->sender);
   printf("\tSubject: %s\n", email->subject);
   printf("\tDate: %s\n\n", email->date);
}

void handleRead(MaxHeap *heap) {
   /* Silently discard the top email. If the heap is empty,
    * heapExtractMax simply returns 0 and nothing happens --
    * no crash, no output, matching the "handle gracefully"
    * requirement. */
   heapRemoveMax(heap);
}

void handleCount(MaxHeap *heap) {
   if (heap->size == 1) {
       printf("There is 1 email to read.\n\n");
   } else {
       printf("There are %d emails to read.\n\n", heap->size);
   }
}

/* ============================================================
* Main: read commands one line at a time from a file named on
* the command line, or from stdin if no filename is given.
* ============================================================ */
int main(int argc, char *argv[]) {
   FILE *input = stdin;

   if (argc > 1) {
       input = fopen(argv[1], "r");
       if (input == NULL) {
           fprintf(stderr, "Could not open file: %s\n", argv[1]);
           return 1;
       }
   }

   MaxHeap heap;
   heapInit(&heap);

   char line[MAX_LINE_LEN];
   unsigned long nextArrivalOrder = 0;
   while (fgets(line, sizeof(line), input) != NULL) {
       /* Strip trailing newline / carriage return. */
       line[strcspn(line, "\r\n")] = '\0';

       if (strlen(line) == 0) {
           continue; /* ignore blank lines */
       }

       if (strncmp(line, "EMAIL ", 6) == 0) {
           processEmailCommand(&heap, line, nextArrivalOrder++);
       } else if (strcmp(line, "NEXT") == 0) {
           handleNext(&heap);
       } else if (strcmp(line, "READ") == 0) {
           handleRead(&heap);
       } else if (strcmp(line, "COUNT") == 0) {
           handleCount(&heap);
       } else {
           fprintf(stderr, "Skipping unrecognized command: %s\n", line);
       }
   }

   if (input != stdin) {
       fclose(input);
   }
   heapFree(&heap);
   return 0;
}
