// EECS 348 Assignment 1
// Program that prioritizes emails for a busy CEO by using maxheap to implement a priority queue. Emails will be placed in queue based on sender category, subject line, and date.
// Inputs: Email and command txt file
// Outputs: command line output that gives information about emails and the amount left to read
// Source: Generated by Claude: improvemented to the code were also made in collaboration with ChatGPT
// Author: Madelyn Armitage
// Creation Date: 09/16/2026
// No collaborators



//Claude code starts below this line

/* ============================================================
* email_priority.c
*
* Prioritizes a CEO's inbox using a MaxHeap-based priority queue.
*
* The MaxHeap is implemented from scratch as a dynamically-growing
* array (a "list-based" heap, as opposed to a pointer/tree-based
* heap). No standard-library or third-party heap module is used --
* every heap operation below (insert, extract-max, sift up/down)
* is written by hand.
*
* -------------------------------------------------------------
* Priority rules
* -------------------------------------------------------------
* 1. Sender category determines the primary priority:
*        Boss            (highest / read first)
*        Subordinate
*        Peer
*        ImportantPerson
*        OtherPerson     (lowest / read last)
*
* 2. When two queued emails share the same category, the NEWER
*    email (by date) is read first.
*
* Both rules are folded into a single numeric key so a standard
* MaxHeap comparison (bigger key = higher priority) handles both
* at once:
*
*        key = categoryRank * 100000000  +  YYYYMMDD
*
* Category rank dominates the comparison (it's multiplied by a
* number bigger than any possible YYYYMMDD value), so category
* always wins first; the date only breaks ties within the same
* category.
*
* -------------------------------------------------------------
* Commands (one per line of the test file)
* -------------------------------------------------------------
*   EMAIL <sender category>,<subject line>,<date>
*          -> insert a new email into the heap
*   NEXT
*          -> PEEK at (do not remove) the highest-priority email
*             and print Sender / Subject / Date. Calling NEXT
*             twice in a row with no READ in between prints the
*             same email both times, since nothing was removed.
*   READ
*          -> POP the highest-priority email off the heap. Prints
*             nothing (the CEO "dealt with it" silently). Calling
*             READ twice in a row with no NEXT in between simply
*             discards the two highest-priority emails, neither
*             of which is ever displayed.
*   COUNT
*          -> print how many unread emails remain in the queue
*
* NEXT/READ on an empty queue is handled gracefully (no crash,
* a friendly message instead of a listing).
*
* -------------------------------------------------------------
* Running
* -------------------------------------------------------------
*   ./email_priority < testfile.txt      (read commands via stdin)
*   ./email_priority testfile.txt        (read commands from a file
*                                          named on the command line)
* Both invocation styles are supported so the grader can use
* whichever it prefers.
* ============================================================ */

#include <stdio.h> //includes standard input and output library
#include <stdlib.h> //provides dynamic memory from library
#include <string.h> //provides string functions like comparison, copying, and splitting
#include <ctype.h> //provides whitespace character detection

#define MAX_SENDER_LEN   16 //sets max sender length to 16 including null terminator
#define MAX_SUBJECT_LEN  256 //sets max subject length to 256 including null terminator
#define MAX_DATE_LEN     11 //sets max date length to 11 including null terminator
#define MAX_LINE_LEN     1024 //sets max line length to 1024 including null terminator
#define INITIAL_CAPACITY 16 //sets initial capacity to 16 including null terminator
#define CATEGORY_PRIORITY_MULTIPLIER 100000000L //ensures sender rank takes priority over date

/* ------------------------------------------------------------
* Email record stored in the heap.
* ------------------------------------------------------------ */
//email structure that defines characteristics of an email type
typedef struct {//opens email structure
   char sender[MAX_SENDER_LEN];    /* sender category, e.g. "Boss"   */
   char subject[MAX_SUBJECT_LEN];  /* subject line (no commas)       */
   char date[MAX_DATE_LEN];        /* MM-DD-YYYY, kept as given       */
   long priorityKey;               /* combined category+date sort key */
   unsigned long arrivalOrder; //stores arrival order to compare priority ties
} Email;// Allows the usage of name "Email" for the structure type

/* ------------------------------------------------------------
* MaxHeap: a growable array of Emails plus a logical size.
* ------------------------------------------------------------ */
typedef struct { //opens up MaxHeap structure
   Email *data; //points to the email array, specifically the first element in the array
   int size; //keeps track of the number of emails stored in the heap
   int capacity; //keeps track of the number of emails that can fit before resizing
} MaxHeap; //gives name MaxHeap to structure

/* ============================================================
* Heap helper / core functions -- all written from scratch.
* ============================================================ */

/* Allocate the heap's backing array. */
void heapInit(MaxHeap *heap) { //initializes an empty MaxHeap
   heap->capacity = INITIAL_CAPACITY; //reserves space for 16 emails
   heap->size = 0; //heap begins with no stored emails
   heap->data = (Email *)malloc(sizeof(Email) * (size_t)heap->capacity); //makes memory used dynamic based on email amount
   if (heap->data == NULL) { //checks if memory allocation failed
       fprintf(stderr, "Fatal: memory allocation failed in heapInit.\n"); //prints an error if one occured
       exit(1); //ends program if there is an error
   }
}

/* Release everything the heap owns. */
void heapFree(MaxHeap *heap) { //releases heap's allocated memory
   free(heap->data); //Returns the allocated email array to the system
   heap->data = NULL; // Prevents the pointer from referencing freed memory
   heap->size = 0; // Records that the heap contains no emails
   heap->capacity = 0; // Records that no array space remains allocated
}

/* Double the backing array's capacity when it fills up. */
void heapGrow(MaxHeap *heap) { // Doubles the heap's storage capacity
   int newCapacity = heap->capacity * 2; // Calculates the doubled capacity
   Email *newData = (Email *)realloc(heap->data, sizeof(Email) * (size_t)newCapacity); // Resizes the existing email array
   if (newData == NULL) { // Checks whether resizing the array failed
       fprintf(stderr, "Fatal: memory allocation failed in heapGrow.\n"); // Reports the failure
       exit(1); // Stops because the new email cannot be stored safely
   } //closes if statement
   heap->data = newData; // Stores the address of the resized array
   heap->capacity = newCapacity; // Updates the heap's available storage count
} //closes void

void swapEmails(Email *first, Email *second) { // Exchanges two emails in the heap
   Email temporary = *first; // Temporarily saves the first email
   *first = *second; // Copies the second email into the first position
   *second = temporary; // Moves the original first email into the second position
} //closes swapEmails

static int hasHigherPriority(const Email *first, const Email *second) { // Compares two emails and returns 1 if the first email has higher priority
   if (first->priorityKey != second->priorityKey) { // Checks whether the emails have different sender/date priority values
       return first->priorityKey > second->priorityKey; // Returns 1 if the first email has the larger priority key and 0 otherwise
   }//closes if statement
   return first->arrivalOrder < second->arrivalOrder;// If the keys match, gives priority to the email that arrived first
}//closes function hasHigherPriority

/* Restore heap order by moving the element at 'index' upward
* toward the root while it is bigger than its parent. */
void siftUp(MaxHeap *heap, int index) {  // Moves a newly inserted email upward until the MaxHeap order is restored
   while (index > 0) { // Repeats while the email is not already at the root
       int parent = (index - 1) / 2; // Calculates the array index of the email's parent
       if (hasHigherPriority(&heap->data[index], &heap->data[parent])) { // Compares sender/date priority
           swapEmails(&heap->data[index], &heap->data[parent]); // Swaps the child and parent so the higher-priority email moves upward
           index = parent; // Updates index to follow the email into its new parent position
       } else { // Runs when the child does not have higher priority than its parent
           break; // Stops because the email is now in the correct heap position
       }//closes else statement
   } //closes while
} //closes siftup function

/* Restore heap order by moving the element at 'index' downward,
* always swapping with the larger of its two children, until
* both children (if any) are smaller or it has none. */
void siftDown(MaxHeap *heap, int index) { // Moves an email downward until heap order is restored
   while (1) { // Continues until the email has no higher-priority child
       int left = 2 * index + 1; // Calculates the left child's index
       int right = 2 * index + 2; // Calculates the right child's index
       int largest = index; // Initially assumes the current email has the highest priority

       if (left < heap->size && // Checks whether the left child exists and has higher priority
           hasHigherPriority(&heap->data[left], &heap->data[largest])) { // Checks whether the left child has higher priority than the current choice
           largest = left;// Records the left child as the highest-priority position
       }// Ends the left-child comparison
       if (right < heap->size && // Checks that the right-child position exists in the heap
           hasHigherPriority(&heap->data[right], &heap->data[largest])) { // Compares the right child with the current highest-priority choice
           largest = right; // Records the right child as the highest-priority position
       } // Ends the right-child comparison
       if (largest == index) { // Checks whether neither child had higher priority than the current email
           break; // Stops the loop because the current email is in the correct position
       } // Ends the heap-order check
       swapEmails(&heap->data[index], &heap->data[largest]); // Swaps the current email with its highest-priority child
       index = largest; // Follows the moved email to its new lower position
   } // Ends the downward movement loop
} // Ends the siftDown function

/* Insert a new email into the heap, keeping heap order. */
void heapInsert(MaxHeap *heap, Email email) { // Inserts a new email into the MaxHeap
   if (heap->size == heap->capacity) { // Checks whether every allocated array position is already occupied
       heapGrow(heap); // Doubles the array capacity to create room for the new email
   } // Ends the capacity check
   heap->data[heap->size] = email; // Places the new email in the next open position at the end of the heap
   siftUp(heap, heap->size); // Moves the new email upward until it reaches the correct priority position
   heap->size++; // Increases the number of emails stored in the heap
} // Ends the heapInsert function

/* Remove and return the highest-priority email.
* Returns 1 and fills *out on success, 0 if the heap is empty. */
int heapRemoveMax(MaxHeap *heap) { // Removes the highest-priority email and returns whether removal succeeded
   if (heap->size == 0) { // Checks whether the heap is empty
       return 0; // Reports that no email could be removed
   } // Ends the empty-heap check
   heap->size--; // Decreases the number of active emails in the heap
   if (heap->size > 0) { // Checks whether at least one email remains after the removal
       heap->data[0] = heap->data[heap->size]; // Moves the last email into the now-empty root position
       siftDown(heap, 0); // Moves the replacement root downward until heap order is restored
   } // Ends the remaining-email check
   return 1; // Reports that the highest-priority email was successfully removed
} // Ends the heapRemoveMax function

/* Look at the highest-priority email without removing it.
* Returns 1 and fills *out on success, 0 if the heap is empty. */
const Email *heapPeek(const MaxHeap *heap) { // Returns the highest-priority email without removing or modifying it
   if (heap->size == 0) { // Checks whether the heap contains any emails
       return NULL; // Returns a null pointer because there is no email to view
   } // Ends the empty-heap check
   return &heap->data[0]; // Returns the address of the root email, which has the highest priority
} // Ends the heapPeek function

/* ============================================================
* Parsing helpers
* ============================================================ */

/* Trim leading/trailing whitespace from a string, in place. */
void trim(char *str) { // Creates a function that removes whitespace from the beginning and end of a string

    int start = 0; // Stores the index of the first character that is not whitespace

    while (isspace((unsigned char)str[start])) { // Continues while the current character is a space, tab, or other whitespace

        start++; // Moves to the next character in the string
    } // Ends the loop that searches for the first non-whitespace character

    if (start > 0) { // Checks whether any leading whitespace was found

        memmove(str, str + start, strlen(str) - (size_t)start + 1); // Shifts the string left and includes the null terminator in the move
    } // Ends the leading-whitespace check

    int len = (int)strlen(str); // Stores the length of the string after removing leading whitespace

    while (len > 0 && isspace((unsigned char)str[len - 1])) { // Continues while the final character is whitespace

        str[len - 1] = '\0'; // Replaces the final whitespace character with the null terminator

        len--; // Decreases the length so the previous character can be checked
    } // Ends the loop that removes trailing whitespace
} // Ends the trim function


int categoryRank(const char *category) { // Returns the numeric priority assigned to a sender category

    if (strcmp(category, "Boss") == 0) return 5; // Gives Boss the highest sender priority

    if (strcmp(category, "Subordinate") == 0) return 4; // Gives Subordinate the second-highest priority

    if (strcmp(category, "Peer") == 0) return 3; // Gives Peer the middle priority

    if (strcmp(category, "ImportantPerson") == 0) return 2; // Gives ImportantPerson the second-lowest priority

    if (strcmp(category, "OtherPerson") == 0) return 1; // Gives OtherPerson the lowest valid sender priority

    return 0; // Returns zero when the sender category is not recognized
} // Ends the categoryRank function


long dateToInt(const char *date) { // Converts an MM-DD-YYYY date string into a comparable YYYYMMDD number

    int month = 0; // Stores the month extracted from the date

    int day = 0; // Stores the day extracted from the date

    int year = 0; // Stores the year extracted from the date

    char extraCharacter; // Stores an unexpected character if anything appears after the year

    if (sscanf(date, "%d-%d-%d%c", &month, &day, &year, // Attempts to read the month, day, year, and any extra character
               &extraCharacter) != 3) { // Requires exactly three successful conversions so extra characters are rejected

        return 0; // Reports that the date is invalid
    } // Ends the date-format validation

    if (month < 1 || month > 12 || day < 1 || day > 31 || year < 1) { // Checks whether the date values are within basic valid ranges

        return 0; // Reports that the date is invalid
    } // Ends the date-range validation

    return (long)year * 10000L + (long)month * 100L + (long)day; // Rearranges the date into YYYYMMDD so newer dates have larger values
} // Ends the dateToInt function


void processEmailCommand(MaxHeap *heap, char *line, // Creates a function that parses and inserts one EMAIL command
                         unsigned long arrivalOrder) { // Receives the email's insertion order for breaking complete ties

    char *emailData = line + 6; // Skips the six characters in "EMAIL " and points to the sender field

    char *senderField = strtok(emailData, ","); // Extracts the sender field before the first comma

    char *subjectField = strtok(NULL, ","); // Extracts the subject field before the second comma

    char *dateField = strtok(NULL, ","); // Extracts the date field after the second comma

    if (senderField == NULL || subjectField == NULL || dateField == NULL) { // Checks whether all three required fields were found

        fprintf(stderr, "Skipping malformed EMAIL line: %s\n", line); // Prints an error message to the standard error stream

        return; // Leaves the function without inserting the malformed email
    } // Ends the missing-field validation

    Email email; // Creates an Email structure to hold the parsed information

    strncpy(email.sender, senderField, MAX_SENDER_LEN - 1); // Copies the sender while leaving room for the null terminator

    email.sender[MAX_SENDER_LEN - 1] = '\0'; // Guarantees that the sender string ends with a null terminator

    trim(email.sender); // Removes extra whitespace from the sender

    strncpy(email.subject, subjectField, MAX_SUBJECT_LEN - 1); // Copies the subject while leaving room for the null terminator

    email.subject[MAX_SUBJECT_LEN - 1] = '\0'; // Guarantees that the subject string ends with a null terminator

    trim(email.subject); // Removes extra whitespace from the subject

    strncpy(email.date, dateField, MAX_DATE_LEN - 1); // Copies the date while leaving room for the null terminator

    email.date[MAX_DATE_LEN - 1] = '\0'; // Guarantees that the date string ends with a null terminator

    trim(email.date); // Removes extra whitespace from the date

    int rank = categoryRank(email.sender); // Converts the sender category into its numeric priority rank

    if (rank == 0) { // Checks whether the sender category was invalid

        fprintf(stderr, "Skipping email with invalid sender category: %s\n", // Begins an error message for an invalid sender
                email.sender); // Inserts the invalid sender category into the error message

        return; // Leaves the function without inserting the invalid email
    } // Ends the sender validation

    long dateVal = dateToInt(email.date); // Converts the date into a number that can be compared

    if (dateVal == 0) { // Checks whether the date conversion failed

        fprintf(stderr, "Skipping email with invalid date: %s\n", email.date); // Prints an invalid-date error message

        return; // Leaves the function without inserting the invalid email
    } // Ends the date validation

    email.priorityKey = // Begins assigning the email's combined sender and date priority

        (long)rank * CATEGORY_PRIORITY_MULTIPLIER + dateVal; // Makes sender rank primary and uses the date to break sender-category ties

    email.arrivalOrder = arrivalOrder; // Stores when the email was inserted to break complete priority ties

    heapInsert(heap, email); // Inserts the completed email into the MaxHeap
} // Ends the processEmailCommand function


void handleNext(const MaxHeap *heap) { // Handles a NEXT command without changing the heap

    const Email *email = heapPeek(heap); // Gets a read-only pointer to the highest-priority email

    if (email == NULL) { // Checks whether the heap was empty

        printf("No emails to read.\n\n"); // Tells the user that no email is available

        return; // Leaves the function because there is no email to display
    } // Ends the empty-heap check

    printf("Next email:\n"); // Prints a heading for the next email

    printf("\tSender: %s\n", email->sender); // Displays the highest-priority email's sender

    printf("\tSubject: %s\n", email->subject); // Displays the highest-priority email's subject

    printf("\tDate: %s\n\n", email->date); // Displays the highest-priority email's date followed by a blank line
} // Ends the handleNext function


void handleRead(MaxHeap *heap) { // Handles a READ command by removing the highest-priority email

    heapRemoveMax(heap); // Silently removes the highest-priority email and safely does nothing if the heap is empty
} // Ends the handleRead function


void handleCount(MaxHeap *heap) { // Handles a COUNT command by displaying the number of unread emails

    if (heap->size == 1) { // Checks whether exactly one unread email remains

        printf("There is 1 email to read.\n\n"); // Displays the grammatically correct singular message
    } else { // Runs when the number of emails is zero or greater than one

        printf("There are %d emails to read.\n\n", heap->size); // Displays the current number of unread emails
    } // Ends the singular-versus-plural check
} // Ends the handleCount function


int main(int argc, char *argv[]) { // Begins the program and receives command-line arguments

    FILE *input = stdin; // Uses standard input unless a test filename is provided

    if (argc > 1) { // Checks whether the user supplied a filename as a command-line argument

        input = fopen(argv[1], "r"); // Opens the supplied file in read-only mode

        if (input == NULL) { // Checks whether the file failed to open

            fprintf(stderr, "Could not open file: %s\n", argv[1]); // Prints the filename that could not be opened

            return 1; // Ends the program with an error status
        } // Ends the file-opening error check
    } // Ends the command-line filename check

    MaxHeap heap; // Creates the MaxHeap that will store the CEO's unread emails

    heapInit(&heap); // Initializes the heap and dynamically allocates its email array

    char line[MAX_LINE_LEN]; // Creates a character array for storing one input line at a time

    unsigned long nextArrivalOrder = 0; // Starts the email arrival counter at zero

    while (fgets(line, sizeof(line), input) != NULL) { // Reads and processes each line until the end of the input

        line[strcspn(line, "\r\n")] = '\0'; // Finds and removes the first newline or carriage-return character

        if (strlen(line) == 0) { // Checks whether the current line is empty

            continue; // Skips the empty line and begins the next loop iteration
        } // Ends the empty-line check

        if (strncmp(line, "EMAIL ", 6) == 0) { // Checks whether the line begins with the EMAIL command

            processEmailCommand(&heap, line, nextArrivalOrder++); // Parses the email, inserts it, and then increases the arrival counter
        } else if (strcmp(line, "NEXT") == 0) { // Checks whether the line is exactly the NEXT command

            handleNext(&heap); // Displays the highest-priority email without removing it
        } else if (strcmp(line, "READ") == 0) { // Checks whether the line is exactly the READ command

            handleRead(&heap); // Removes the highest-priority email without displaying it
        } else if (strcmp(line, "COUNT") == 0) { // Checks whether the line is exactly the COUNT command

            handleCount(&heap); // Displays the current number of unread emails
        } else { // Runs when the line does not match any recognized command

            fprintf(stderr, "Skipping unrecognized command: %s\n", line); // Reports the unrecognized command to the standard error stream
        } // Ends the command-selection statements
    } // Ends the input-reading loop

    if (input != stdin) { // Checks whether the program opened a file instead of using standard input

        fclose(input); // Closes the opened test file
    } // Ends the file-closing check

    heapFree(&heap); // Releases the dynamically allocated heap memory

    return 0; // Ends the program successfully
} // Ends the main function